[package]
name = "vga"
version = "0.1.0"
authors = ["Hawk Weisman <hi@hawkweisman.me>"]

[features]
default = []
system_term = ["spin"]
log = ["system_term"]

[dependencies.spin]
version = "0.3.5"
optional = true
