# sudo: required
language: rust

rust:
    - nightly

sudo: false

notifications:
    email:
        on_success: never
        on_failure: change

addons:
  apt:
    packages:
      - nasm
      - build-essential
      - xorriso

install:
  # - sudo curl -sf https://raw.githubusercontent.com/brson/multirust/master/blastoff.sh | sh -s -- --yes
  # - multirust default nightly
  - git submodule update
  - make runtime

script:
    - make
