[package]
name = "sos_kernel"
version = "0.1.0"
authors = [ # hacked around by
            "Hawk Weisman <hi@hawkweisman.me>"
          , # based on code by
            "Philipp Oppermann <dev@phil-opp.com>"
          ]

[lib]
crate-type = ["staticlib"]

[dependencies]
rlibc = "0.1.4"
bitflags-core = "0.3.4"

[dependencies.spin]
git = "https://github.com/mvdnes/spinlock-rs.git"
rev = "b105b38c64f30f94aa44fc7f116b2adc0759f192"

[dependencies.sos_alloc]
path = "lib/sos_alloc"
features = ["buddy_as_system"]

[dependencies.sos_multiboot2]
path = "lib/sos_multiboot2"

[dependencies.sos_vga]
path = "lib/sos_vga"
features = ["system_term"]
