[package]
name = "sos_kernel"
version = "0.1.0"
authors = [ # hacked around by
            "Hawk Weisman <hi@hawkweisman.me>"
          , # based on code by
            "Philipp Oppermann <dev@phil-opp.com>"
          ]

[lib]
crate-type = ["staticlib"]

[profile.dev]
panic = "abort"

[profile.release]
panic = "abort"

[features]
default = []

[dependencies]
rlibc = "0.1.4"
spin = "0.3.5"
once = "0.3.2"
bitflags = "0.7"

[dependencies.sos_alloc]
path = "lib/sos_alloc"
features = ["buddy_as_system"]

[dependencies.sos_vga]
path = "lib/sos_vga"
features = ["system_term"]

[dependencies.clippy]
version = "0.0.60"
optional = true
