[package]
name = "sos_kernel"
version = "0.1.0"
authors = [ # hacked around by
            "Hawk Weisman <hi@hawkweisman.me>"
          , # based on code by
            "Philipp Oppermann <dev@phil-opp.com>"
          ]

[lib]
crate-type = ["staticlib"]

[features]
default = []

[dependencies]
rlibc = "0.1.4"
spin = "0.3.5"

[dependencies.bitflags]
version = "0.4.0"
features = ["no_std"]

[dependencies.sos_alloc]
path = "lib/sos_alloc"
features = ["buddy_as_system"]

[dependencies.sos_vga]
path = "lib/sos_vga"
features = ["system_term"]

[dependencies.clippy]
version = "*"
optional = true
